version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      DB_HOST: ng_db
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_NAME: your_postgres_db_name
      DB_PORT: 5432
      ALLOWED_ORIGINS: your_allowed_origins_value
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  db:
    container_name: ng_db
    image: postgres:15.1
    platform: linux/x86_64
    ports:
      - "3002:5432"
    environment:
      - POSTGRES_PASSWORD=123456
    restart: 'always'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      timeout: 10s
      retries: 5
